// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reserve_final.Data;

#nullable disable

namespace Reserve_final.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reserve_final.Data.Model.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Center");
                });

            modelBuilder.Entity("Reserve_final.Data.Model.CenterVaccine", b =>
                {
                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<int>("VaccineId")
                        .HasColumnType("int");

                    b.HasKey("CenterId", "VaccineId");

                    b.HasIndex("VaccineId");

                    b.ToTable("CenterVaccines");
                });

            modelBuilder.Entity("Reserve_final.Data.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoseNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PreviousVaccinationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("centerId")
                        .HasColumnType("int");

                    b.Property<int>("vaccineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("centerId");

                    b.HasIndex("vaccineId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Reserve_final.Data.Model.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precautions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeGap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vaccine");
                });

            modelBuilder.Entity("Reserve_final.Data.Model.CenterVaccine", b =>
                {
                    b.HasOne("Reserve_final.Data.Model.Center", "Center")
                        .WithMany("CenterVaccines")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reserve_final.Data.Model.Vaccine", "Vaccine")
                        .WithMany("CenterVaccines")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Vaccine");
                });

            modelBuilder.Entity("Reserve_final.Data.Model.Reservation", b =>
                {
                    b.HasOne("Reserve_final.Data.Model.Center", "center")
                        .WithMany("reservations")
                        .HasForeignKey("centerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reserve_final.Data.Model.Vaccine", "vaccine")
                        .WithMany("Reservations")
                        .HasForeignKey("vaccineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("center");

                    b.Navigation("vaccine");
                });

            modelBuilder.Entity("Reserve_final.Data.Model.Center", b =>
                {
                    b.Navigation("CenterVaccines");

                    b.Navigation("reservations");
                });

            modelBuilder.Entity("Reserve_final.Data.Model.Vaccine", b =>
                {
                    b.Navigation("CenterVaccines");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
